sudo: required
language: go
go:
  - "1.16"
services:
- docker
env:
  global:
  - IMAGE=leachim2k/go-shorten
  - YES=1
script:
- make test
- make push-container clean
cache:
  directories:
  - ".gocache"
  - "bin"
